version: "5.0"

services:
  database:
    image: pgvector/pgvector:pg17-trixie
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_DATABASE
    env_file:
      - path: .env
        required: true
    networks:
      - api
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  api:

volumes:
  postgres-data:
